default: &default
  adapter: mysql2
  encoding: utf8
  username: paresh
  password: vinsol
  socket: /private/tmp/mysql.sock
  
development:
  <<: *default
  database: depot_development

test:
  <<: *default
  database: depot_test

staging:
  <<: *default
  database: depot_staging

production:
  <<: *default
  database: depot_production
