default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: vinsol
  socket: /var/run/mysqld/mysqld.soc
  
development:
  <<: *default
  database: depot_development

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: depot_production
