octopus:
  environments:
    - production
  replicated: true
  fully_replicated: true
  production:
    slave1:
      adapter: mysql2
      host: 52.11.190.204
      database: depot_production
      username: paresh
      password: vinsol
